In [1]:
# Cross Validation
'''
Cross validation is a technique to determine which algo is the best for a particular dataset, and how to choose that algo from 
Linear Regression, Logistic Regression, SVM, Random Forest, Decision Tree?
'''

'\nCross validation is a technique to determine which algo is the best for a particular dataset, and how to choose that algo from \nLinear Regression, Logistic Regression, SVM, Random Forest, Decision Tree?\n'

In [2]:
#  K Fold Cross Validation
'''
We divide our let say 100 samples into folds of 5 that means in each sample we have 20 samples and run multiple iterations.
In 1st iteration we take sample 2 to 5 for training and 1st sample to test the data
In 2nd iteration we take sample 1, 3 to 5 for training and 2nd sample to test the data, and so on.
And finally take the average of all the 5 scores.
'''

'\nWe divide our let say 100 samples into folds of 5 that means in each sample we have 20 samples and run multiple iterations.\nIn 1st iteration we take sample 2 to 5 for training and 1st sample to test the data\nIn 2nd iteration we take sample 1, 3 to 5 for training and 2nd sample to test the data, and so on.\nAnd finally take the average of all the 5 scores.\n'

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn import tree
import pandas as pd
from sklearn.datasets import load_digits

In [5]:
digits = load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [6]:
df = pd.DataFrame(digits.data)
df.head()

0    1    2     3     4     5    6    7    8    9   ...   54   55   56  \
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  0.0  0.0  0.0  ...  5.0  0.0  0.0   
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  0.0  0.0  8.0  ...  9.0  0.0  0.0   
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

    57   58    59    60    61   62   63  
0  0.0  6.0  13.0  10.0   0.0  0.0  0.0  
1  0.0  0.0  11.0  16.0  10.0  0.0  0.0  
2  0.0  0.0   3.0  11.0  16.0  9.0  0.0  
3  0.0  7.0  13.0  13.0   9.0  0.0  0.0  
4  0.0  0.0   2.0  16.0   4.0  0.0  0.0  

[5 rows x 64 columns]

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2)

In [64]:
y_train

array([0, 1, 2, ..., 7, 4, 4])

In [24]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

/home/home/Documents/Projects/machine_learning/env/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9722222222222222

In [25]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9833333333333333

In [26]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9861111111111112

In [27]:
t = tree.DecisionTreeClassifier()
t.fit(X_train, y_train)
t.score(X_test, y_test)

0.8555555555555555

In [28]:
## K - fold API

In [38]:
from sklearn.model_selection import KFold
kf = KFold()
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [39]:
for train_index, test_index in kf.split(range(1,11)):
    print(train_index, test_index)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [40]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [44]:
from sklearn.model_selection import StratifiedKFold # similar to k fold, it will divide the classification categories in a uniform way

In [58]:
folds = StratifiedKFold(n_splits=10)

In [68]:
from sklearn.preprocessing import MinMaxScaler
min_max_scaler = MinMaxScaler()
X_train_minmax = min_max_scaler.fit_transform(X_train)


In [73]:
logistic = []
svm_ = []
ran_for = []
dec_tree = []
for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    # Feature scaling for testing and training dataset
    X_train = min_max_scaler.fit_transform(X_train)
    X_test = min_max_scaler.fit_transform(X_test)
    logistic.append(get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    svm_.append(get_score(SVC(C=12.0), X_train, X_test, y_train, y_test))
    ran_for.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))
    dec_tree.append(get_score(tree.DecisionTreeClassifier(), X_train, X_test, y_train, y_test))

In [75]:
import numpy as np
print(np.mean(logistic))
print(np.mean(svm_))
print(np.mean(ran_for))
print(np.mean(dec_tree))

0.9409900682805711
0.9821818746120423
0.946576660459342
0.8352545003103662


In [76]:
print(np.mean(svm_))

0.9821818746120423


In [77]:
print(np.mean(svm_))

0.9821818746120423


In [79]:
# we don't have to write the above code, instead can use a method from 'cross_val_score'
from sklearn.model_selection import cross_val_score

In [82]:
data = min_max_scaler.fit_transform(digits.data)

In [83]:
cross_val_score(LogisticRegression(), data, digits.target)

array([0.94166667, 0.89444444, 0.94707521, 0.96935933, 0.90250696])

In [84]:
cross_val_score(SVC(), data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [85]:
cross_val_score(RandomForestClassifier(), data, digits.target)

array([0.925     , 0.91388889, 0.9637883 , 0.95543175, 0.92200557])